Vidly/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Vidly.Models
{
    public class Customer
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsSubScribedToNewsLetter { get; set; }
        public MembershipType MembershipType { get; set; }
        public byte MembershipTypeId { get; set; }
    }
}

Vidly/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vidly.Models;
using Vidly.ViewModels;

namespace Vidly.Controllers
{
    public class CustomerController : Controller
    {
        static List<Customer> customer = new List<Customer>
            {
                new Customer  {Name = "Courtney Oborn", Id = 1 },
                new Customer  {Name = "Christopher Johnson", Id = 2 }
            };

        RandomMovieViewModel ViewModelListOfCustomers = new RandomMovieViewModel
        {
            Customer = customer,

        };
        [Route("Customer/ListOfCustomers")]
        public ActionResult ListOfCustomers()
        {

            return View(ViewModelListOfCustomers);

        }

        [Route("Customer/Details/{Id}")]
        public ActionResult Details(int Id)
        {
            Customer customerfound = ViewModelListOfCustomers.Customer.Find(x => x.Id == Id);
            if (customerfound == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(customerfound);
            }
       
        }
    }
}

Vidly/Views/Customer/Details.cshtml
@model Vidly.Models.Customer

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Customers</h1>
<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }
</style>

<table class="Customers">
    <tr><td>@Model.Name</td></tr>
</table>

Vidly/Views/Customer/ListOfCustomers.cshtml
@model Vidly.ViewModels.RandomMovieViewModel
@{
    ViewBag.Title = "ListOfCustomers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>Customers</h1>
<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }
    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }
    tr:nth-child(even) {
        background-color: #dddddd;
    }
</style>
@if(!Model.Customer.Any())
 {
    <p>We don't have any customers yet.</p>
 }
  else 
  {
    <table class="Customers">
        <th>Customer</th>
        @foreach (var customer in Model.Customer)
         {
            <tr><td>@Html.ActionLink(customer.Name, "Details", "Customer", new { Id = customer.Id }, null)</td></tr>
         }

    </table>
  }