Vidly/Models/Movie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Vidly.Models
{
    public class Movie
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

Vidly/Controllers/MoviesController.cs
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;
using Vidly.Models;
using Vidly.ViewModels;

namespace Vidly.Controllers
{
    public class MovieController : Controller
    {
       static List<Movie> movie = new List<Movie>
            {
                new Movie  { Name = "Shrek", Id = 1},
                new Movie  { Name = "Wall-e", Id = 2}
            };

        RandomMovieViewModel viewModelMovies = new RandomMovieViewModel
        {
            Movie = movie,
        };

        [Route("Movie/MovieTitles")]

        public ActionResult MovieTitles()
        {

              return View(viewModelMovies);
        }

        [Route("Movie/Details/{Id}")]

        public ActionResult Details(int Id)
        {
            Movie movieFound = viewModelMovies.Movie.Find(x => x.Id == Id);
            if(movieFound == null)
            {
              return  HttpNotFound();
            }
            else
            {
                return View(movieFound);
            }
            
        }


    }
}

Vidly/Views/Movie/Details.cshtml
@model Vidly.Models.Movie

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Movies</h1>
<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }
</style>

<table>
    <tr>Movie</tr>
    <tr><td>@Model.Name</td></tr>
</table>

Vidly/Views/Movie/MovieTitles.cshtml
@model Vidly.ViewModels.RandomMovieViewModel

@{
    ViewBag.Title = "MovieTitles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>Movie Titles</h1>
<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }
</style>
<table class="Movies">

    <th>Movie</th>
    @foreach (var movie in Model.Movie)
    {
    <tr><td>@Html.ActionLink(movie.Name, "Details", "Movie", new { Id = movie.Id }, null)</td></tr>
    }
</table>